# Generated by Django 4.2.7 on 2023-11-22 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_order_total_alter_order_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='tax',
            new_name='shipping_fee',
        ),
    ]
