# Generated by Django 4.2.7 on 2023-11-20 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_available',
        ),
    ]
